### ISSUE TITLE
Issue while verifying contracts

### ISSUE THREAD

**Issue by MattiaGo** [PatrickAlphaC/hardhat-nft-fcc#57]
When I deploy the 3 contracts on the goerli test net the BasicNft succeed while the random and the dynamic ones fails the verification on etherscan.

What's wrong?

Here the message with the DynamicSvgNft:

-----
We tried verifying your contract DynamicSvgNft without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/DynamicSvgNft.sol:DynamicSvgNft at 0x2A903e630A66A5470571E4d817E618480D7F8fF8
for verification on the block explorer. Waiting for verification result...

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/mattia/sol_js_code/8_nft/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:350:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Environment._runTaskDefinition (/Users/mattia/sol_js_code/8_nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/Users/mattia/sol_js_code/8_nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at verify (/Users/mattia/sol_js_code/8_nft/utils/verify.js:9:9)
    at Object.module.exports [as func] (/Users/mattia/sol_js_code/8_nft/deploy/02-deploy-dynamic-svg-nft.js:35:9)
    at DeploymentsManager.executeDeployScripts (/Users/mattia/sol_js_code/8_nft/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1219:22)
    at DeploymentsManager.runDeploy (/Users/mattia/sol_js_code/8_nft/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/Users/mattia/sol_js_code/8_nft/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/Users/mattia/sol_js_code/8_nft/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
------

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
