### ISSUE TITLE
{ProviderError: HttpProviderError} deploying "DynamicSvgNft"exceeds block gas limit

### ISSUE THREAD

**Issue by myselfunknown00** [PatrickAlphaC/hardhat-nft-fcc#70]
Whenever I try to deploy my DynamicSvgNft smart contract on goerli it throws an error, can anyone help ? It's been days :)

``` 
deploying "DynamicSvgNft"exceeds block gas limit {"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)\n    at LocalAccountsProvider.request (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":-32000,"_isProviderError":true} ProviderError: HttpProviderError
    at HttpProvider.request (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
An unexpected error occurred:

Error: ERROR processing /home/ubuntu/hardhat-nft-fcc/deploy/03-deploy-dynamic-svg-nft.js:
ProviderError: HttpProviderError
    at HttpProvider.request (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/providers/accounts.ts:181:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.executeDeployScripts (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.runDeploy (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat-deploy/src/index.ts:422:5)
    at Environment._runTaskDefinition (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at SimpleTaskDefinition.action (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat-deploy/src/index.ts:568:32)
    at Environment._runTaskDefinition (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at SimpleTaskDefinition.action (/home/ubuntu/hardhat-nft-fcc/node_modules/hardhat-deploy/src/index.ts:653:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```


i tried to add "blockGasLimit" in goerli but it didn't work

`` goerli: { url: GOERLI_RPC_URL, accounts: [PRIVATE_KEY], chainId: 5, blockConfirmations: 6, blockGasLimit: 100000000429720, },``

and it deploys on hardhat without any error.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
